FROM node:17

WORKDIR /etc/mlg2048
ADD ./package.json ./
ADD ./package-lock.json ./
RUN npm install ./
ADD webpack.common.js ./
ADD webpack.dev.js ./
VOLUME /etc/mlg2048/src

EXPOSE 80
CMD npm run dev
